name = "exam-system-cache"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

# KV 命名空间绑定
# 请将下面的 ID 替换为你实际创建的 KV 命名空间 ID
[[kv_namespaces]]
binding = "KV_STATIC"
id = "your-kv-namespace-id"  # 替换为生产环境的 KV 命名空间 ID
preview_id = "your-preview-kv-namespace-id"  # 替换为预览环境的 KV 命名空间 ID

# 环境变量（可选）
[vars]
ORIGIN_SERVER = "https://your-actual-backend.com"  # 替换为你的后端服务器地址
CACHE_PURGE_TOKEN = "your-secure-cache-purge-token"  # 缓存清理授权 token

# 开发环境配置
[env.development]
name = "exam-system-cache-dev"
vars = { ORIGIN_SERVER = "http://localhost:3000" }

# 预览环境配置
[env.preview]
name = "exam-system-cache-preview"
vars = { ORIGIN_SERVER = "https://your-staging-backend.com" }

# 生产环境配置
[env.production]
name = "exam-system-cache-prod"
vars = { ORIGIN_SERVER = "https://your-production-backend.com" }

# Worker 配置
[build]
command = ""

# 限制和配额
[limits]
cpu_ms = 50

# 触发器配置（可选）
# 如果你想使用自定义域名，可以在这里配置
# [[routes]]
# pattern = "api.yourdomain.com/*"
# zone_name = "yourdomain.com"